base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from clientes import views

handler404 = 'clientes.views.custom_page_not_found_view'
handler500 = 'clientes.views.custom_error_view'
handler403 = 'clientes.views.custom_permission_denied_view'
handler400 = 'clientes.views.custom_bad_request_view'

urlpatterns = [
    path('', include('clientes.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

clientes/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views

app_name = 'clientes'

urlpatterns = [
    path("", views.video_machine_pro, name="video_machine_pro"),
    path("redirect-whatsapp", views.redirect_whatsapp, name="redirect_whatsapp"),
    path("politicas", views.politicas, name="politicas"),
    path("termos", views.termos, name="termos"),
    path("robo-video-maker", views.robo_video_maker, name="robo_video_maker"),
    path("download-turbo-list", views.download_turbo_list, name="download_turbo_list"),
    path("video-machine-pro", views.video_machine_pro, name="video_machine_pro"),

    
    path('kiwify-test-dm/<str:mac>', views.kiwify_test_dm),
    path('kiwify-dm', views.kiwify_dm),
    path('kiwify-vmp', views.kiwify_vmp),


    path('hotmart-test/<str:mac>', views.hotmart_test),
    path('hotmart-rdm', views.hotmart_rdm),
    path('hotmart-rvm', views.hotmart_rvm),
    

    path('robo-download-machine-post', views.download_machine_post),
    path('robo-video-maker-test-post', views.video_maker_test_post),
]

clientes/models.py
from django.contrib.auth.models import User
from django.db import models


class Clientes(models.Model):
    nome                = models.CharField(max_length = 150, default='', blank=True, null=True)
    email               = models.CharField(max_length = 150)
    num_contato         = models.CharField(max_length = 15, blank=True, null=True)
    mac1                = models.CharField(max_length = 150, default='', blank=True, null=True)
    mac2                = models.CharField(max_length = 150, default='', blank=True, null=True)
    mac3                = models.CharField(max_length = 150, default='', blank=True, null=True)
    mac4                = models.CharField(max_length = 150, default='', blank=True, null=True)
    mac5                = models.CharField(max_length = 150, default='', blank=True, null=True)
    mac6                = models.CharField(max_length = 150, default='', blank=True, null=True)
    conta               = models.ForeignKey(User, on_delete=models.CASCADE, related_name='perfil', blank=True, null=True)
    data                = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.email

clientes/forms/login_form.py
from django import forms


class LoginForm(forms.Form):
    username  = forms.CharField(max_length = 150)
    password  = forms.CharField(
        widget=forms.PasswordInput()                 
    )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['username'].widget.attrs['placeholder'] = 'Nome de usuário'
        for field in self.fields.values():
            field.widget.attrs['class'] = 'w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600'
    

clientes/forms/register_form.py
from django import forms
from django.contrib.auth.models import User
from genericpath import exists


class RegisterForm(forms.ModelForm):
    password2 = forms.CharField(
        widget=forms.PasswordInput(),
        label='Repetir Senha'
    )
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        ]
        widgets = {
            'password': forms.PasswordInput()
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['username'].widget.attrs['placeholder'] = 'Nome de usuário'
        for field in self.fields.values():
            field.widget.attrs['class'] = 'w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600'
            field.widget.attrs['placeholder'] = field.label
            
            
    def clean_email(self):
        email = self.cleaned_data.get('email', '')
        exists = User.objects.filter(email =email).exists()
        
        if exists:
            raise forms.ValidationError('Esse email já existe na base de dados')
        
        return email
            
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')
        
        if password != password2:
            raise forms.ValidationError({
                'password': 'O campo senha deve ser repetido',
                'password2': 'Repita o mesmo valor do campo de senha',
            })
    

clientes/views.py
import hmac
import json
from hashlib import sha1

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.db.models.query_utils import Q
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt

from . import forms
from .models import Clientes

# Create your views here.

def frontpage(request):
    return render(request, 'clientes/pages/frontpage.html')

def robo_video_maker(request):
    return render(request, 'clientes/pages/video_maker.html')

def download_turbo_list(request):
    return render(request, 'clientes/pages/download_turbo_list.html')

def video_machine_pro(request):
    return render(request, 'clientes/pages/video_machine_pro.html')

def politicas(request):
    return render(request, 'clientes/pages/politicas.html')

def termos(request):
    return render(request, 'clientes/pages/termos.html')

def redirect_whatsapp(request):
    return render(request, 'clientes/pages/redirect_whatsapp.html')



def kiwify_test_dm(request, mac):

    # Procura o mac e retorna uma resposta

    cliente = Clientes.objects.filter(Q(mac1=mac) | Q(mac2=mac) | Q(mac3=mac) | Q(mac4=mac) | Q(mac5=mac) | Q(mac6=mac)).first()

    if cliente:
        status = 200
        data = {
            'register': True,
            'version': '0.0.1',
            'url': 'https://robozinhos.com.br/83lrfhsr7jfk9'
            }
    else:
        status = 500
        data = {
            'register': False,
            }

    print('Testa se o mac existe')

    return JsonResponse(data=data, status=status)



@csrf_exempt
def kiwify_dm(request):
    
    # Validar token da Kiwify
    token = "angcqay2hrm".encode('utf-8')

    received_json_data = request.body.decode('utf-8')

    hexa = hmac.new(token, received_json_data.encode('utf-8'), sha1).hexdigest()

    if hexa == request.GET.get('signature', ''):

        loads_received_json_data = json.loads(received_json_data)

        # json_formatted_str = json.dumps(loads_received_json_data, indent=2)

        # print(json_formatted_str)        

        cliente = Clientes.objects.create(email=loads_received_json_data.get("Customer").get("email"))
        cliente.save()

        return JsonResponse(data={'status': 'ok'}, status=200)
    else:
        print('Token não confere')
        return JsonResponse(data={'error': 'Incorrect signature'}, status=400)


@csrf_exempt
def kiwify_vmp(request):

    # Validar token da Kiwify
    token = "l1egqzkfupy".encode('utf-8')

    received_json_data = request.body.decode('utf-8')

    hexa = hmac.new(token, received_json_data.encode('utf-8'), sha1).hexdigest()

    if hexa == request.GET.get('signature', ''):

        loads_received_json_data = json.loads(received_json_data)

        # json_formatted_str = json.dumps(loads_received_json_data, indent=2)

        # print(json_formatted_str)        

        cliente = Clientes.objects.create(email=loads_received_json_data.get("Customer").get("email"))
        cliente.save()

        return JsonResponse(data={'status': 'ok'}, status=200)
    else:
        print('Token não confere')
        return JsonResponse(data={'error': 'Incorrect signature'}, status=400)


def hotmart_test(request, mac):

    cliente = Clientes.objects.filter(Q(mac1=mac) | Q(mac2=mac) | Q(mac3=mac) | Q(mac4=mac) | Q(mac5=mac) | Q(mac6=mac)).first()

    if cliente:
        status = 200
        data = {
            'register': True,
            'version': '0.0.8',
            'url': 'https://robozinhos.com.br/20fjnct59ghj39'
            }
    else:
        status = 500
        data = {
            'register': False,
            }

    print('Testa se o mac existe')

    return JsonResponse(data=data, status=status)

@csrf_exempt
def hotmart_rdm(request):

    if request.POST.get("hottok") == 'ysewXlAZI1iHdUFqC4ZcV1J5RLhiVe518471':
        print('Passou no post')
        cliente = Clientes.objects.create(email=request.POST.get('email'))
        cliente.save()

        return JsonResponse(data={'status': 'ok'}, status=200)

    received_json_data = request.body.decode('utf-8')

    loads_received_json_data = json.loads(received_json_data)

    json_formatted_str = json.dumps(loads_received_json_data, indent=2)
    
    print(json_formatted_str)

    if loads_received_json_data.get("hottok") == 'ysewXlAZI1iHdUFqC4ZcV1J5RLhiVe518471':        

        cliente = Clientes.objects.create(email=loads_received_json_data.get("data").get("buyer").get('email'))
        cliente.save()

        return JsonResponse(data={'status': 'ok'}, status=200)

    else:
        print('Token não confere')
        return JsonResponse(data={'error': 'hottok incorreto'}, status=400)

@csrf_exempt
def hotmart_rvm(request):

    if request.POST.get("hottok") == 'ysewXlAZI1iHdUFqC4ZcV1J5RLhiVe518471':
        print('Passou no post')
        cliente = Clientes.objects.create(email=request.POST.get('email'))
        cliente.save()

        return JsonResponse(data={'status': 'ok'}, status=200)

    received_json_data = request.body.decode('utf-8')

    loads_received_json_data = json.loads(received_json_data)

    json_formatted_str = json.dumps(loads_received_json_data, indent=2)
    
    print(json_formatted_str)

    if loads_received_json_data.get("hottok") == 'ysewXlAZI1iHdUFqC4ZcV1J5RLhiVe518471':        

        cliente = Clientes.objects.create(email=loads_received_json_data.get("data").get("buyer").get('email'))
        cliente.save()

        return JsonResponse(data={'status': 'ok'}, status=200)

    else:
        print('Token não confere')
        return JsonResponse(data={'error': 'hottok incorreto'}, status=400)


@csrf_exempt
def download_machine_post(request):

    print('passou na tentativa de pegar o post')
    received_json_data = json.loads(request.body.decode("utf-8"))

    print(received_json_data)

    if received_json_data['nome'] and received_json_data['email'] and received_json_data['codigo']:

        cliente = Clientes.objects.filter(Q(email=received_json_data['email'])).filter(Q(mac1__exact='') | Q(mac1__isnull=True)).first()


        if cliente:
            cliente.nome = received_json_data['nome']
            cliente.mac1 = received_json_data['codigo']
            cliente.save()
            
            status = 200
            data = {
                'success': True,
                }
        else:
            status = 500
            data = {
                'success': False,
                }
    else:
        status = 500
        data = {
            'success': False,
            }

    return JsonResponse(data=data, status=status)


@csrf_exempt
def video_maker_test_post(request):

    print('passou na tentativa de pegar o post')
    received_json_data = json.loads(request.body.decode("utf-8"))

    print(received_json_data)

    if received_json_data['nome'] and received_json_data['email'] and received_json_data['codigo']:

        cliente = Clientes.objects.filter(Q(email=received_json_data['email'])).filter(Q(mac1__exact='') | Q(mac1__isnull=True)).first()


        if cliente:
            cliente.nome = received_json_data['nome']
            cliente.mac1 = received_json_data['codigo']
            cliente.save()
            
            status = 200
            data = {
                'success': True,
                }
        else:
            status = 500
            data = {
                'success': False,
                }
    else:
        status = 500
        data = {
            'success': False,
            }

    return JsonResponse(data=data, status=status)




def custom_page_not_found_view(request, exception):
    return render(request, "clientes/errors/404.html", status=404)

def custom_error_view(request, exception=None):
    return render(request, "clientes/errors/500.html", status=500)

def custom_permission_denied_view(request, exception=None):
    return render(request, "clientes/errors/403.html", status=403)

def custom_bad_request_view(request, exception=None):
    return render(request, "clientes/errors/400.html", status=400)

clientes/templates/clientes/pages/frontpage.html
{% extends 'global/frontend.html' %}
{% load static %}

{% block titulo %}Automatizando Rotinas{% endblock titulo %}

{% block conteudo %}
<!-- Topo Cinza Escuro -->
<div class="grid grid-cols-5 p-6 min-h-screen items-center bg-gray-700">

  <div></div><!-- Div Da Esquerda Vazia -->

  <!-- Div Central Onde Vai Todo o Centeúdo -->
  <div class="col-span-5 text-white lg:col-span-3 text-center content-center space-y-4">

    <div class="text-3xl font-bold">
      ROBOZINHOS.COM.BR
    </div>
    <div class="text-3xl font-bold">
      Entenda Mais No Vídeo Abaixo
    </div>
    <div class="lg:mx-32">
      <div class="aspect-w-16 aspect-h-9">
        <iframe src="https://www.youtube.com/embed/bkK_DB6Q8b8" title="Como Fazer 50 Vídeos Para Canal Dark, TikTok, Kwai - [ Feito Com Robô Vídeo Maker ]" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </div>
    <div class="text-2xl font-bold">
      Links dos robôs e dos grupos no WhatsApp
    </div>
    <div class="grid lg:flex lg:justify-between">
      <a class="flex flex-col lg:flex-row justify-center p-8 mb-2 lg:mr-4 text-xl uppercase border-solid border-2 border-blue-500 hover:bg-blue-500 text-white rounded" href="{% url 'clientes:robo_video_maker' %}">
        Robô Vídeo Maker
      </a>
      <a class="flex flex-col lg:flex-row justify-center p-8 mb-2 text-xl uppercase border-solid border-2 border-purple-700 hover:bg-purple-700 text-white rounded" href="{% url 'clientes:download_turbo_list' %}">
        Download Turbo List
      </a>
      <a class="flex flex-col lg:flex-row justify-center p-8 mb-2 lg:ml-4 text-xl uppercase border-solid border-2 border-emerald-500 hover:bg-emerald-500 text-white rounded" href="https://viazapi.com.br">
        Bot Respostas ViaZapi
      </a>
    </div>
    <div class="grid lg:flex lg:justify-between">
      <a class="flex lg:flex-row justify-center p-8 mb-2 lg:mr-2 text-xl uppercase bg-green-700 hover:bg-green-500 text-white border-2 border-green-500 hover:border-white hover:border-solid rounded" href="https://viazapi.com.br/grupo/robozinhosgrupo">
        <svg style="color: white" xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16"> <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z" fill="white"></path> </svg>
        
        <span class="flex">
          Grupo Com Aulas Sobre Robôs E Automação
        </span>
      </a>
      <a class="flex lg:flex-row justify-center p-8 mb-2 lg:ml-2 text-xl uppercase bg-green-700 hover:bg-green-500 text-white border-2 border-green-500 hover:border-white hover:border-solid rounded" href="https://viazapi.com.br/grupo/viazapigrupo">
        <svg style="color: white" xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16"> <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z" fill="white"></path> </svg>
        
        <span class="flex">
          Grupo Com Aulas Sobre Vendas No WhatsApp
        </span>
      </a>
    </div>

  </div><!-- Fim Div Central -->

  <div></div><!-- Div Da Direita Vazia -->

</div><!-- Fim Do Topo Cinza Escuro -->



{% endblock conteudo %}

clientes/templates/clientes/pages/politicas.html
{% extends 'global/frontend.html' %}
{% load static %}

{% block titulo %}Políticas de privacidade{% endblock titulo %}

{% block conteudo %}

<div class="grid grid-cols-5 items-center p-4 justify-center bg-red-800 text-white text-2xl">
  <div></div>
  <div class="col-span-5 text-white lg:col-span-3">
    <div class="flex">
      <a class="float-right" href="{% url 'clientes:video_machine_pro' %}">&nbsp<&nbspvoltar</a>
      <div class="text-center w-full">
  
        <b class="-ml-28">TECNOLOGIA</b>
      </div>
    </div>
  </div>
  <div></div>
</div>

<!-- ############################################################################################# -->
<!-- ############################################################################################# -->
<!-- ############################################################################################# -->

<!-- Final Parte Preta -->
<div class="grid grid-cols-5 p-6 min-h-screen items-center bg-white">

  <div></div><!-- Div Da Esquerda Vazia -->

  <!-- Div Central Onde Vai Todo o Centeúdo -->
  <div class="col-span-5 text-gray-700 lg:col-span-3 space-y-4">

    <h2 class="text-3xl"><span>Política Privacidade</span></h2>
    <p><span>A sua privacidade é importante para nós. É política do Vídeo Machine Pro respeitar a sua privacidade em relação a qualquer informação sua que possamos coletar no site <a href="https://videomachinepro.com.br/">Vídeo Machine Pro</a>, e outros sites que possuímos e operamos.</span></p>
    <p><span>Solicitamos informações pessoais apenas quando realmente precisamos delas para lhe fornecer um serviço. Fazemo-lo por meios justos e legais, com o seu conhecimento e consentimento. Também informamos por que estamos coletando e como será usado.</span></p>
    <p><span>Apenas retemos as informações coletadas pelo tempo necessário para fornecer o serviço solicitado. Quando armazenamos dados, protegemos dentro de meios comercialmente aceitáveis ​​para evitar perdas e roubos, bem como acesso, divulgação, cópia, uso ou modificação não autorizados.</span></p>
    <p><span>Não compartilhamos informações de identificação pessoal publicamente ou com terceiros, exceto quando exigido por lei.</span></p>
    <p><span>O nosso site pode ter links para sites externos que não são operados por nós. Esteja ciente de que não temos controle sobre o conteúdo e práticas desses sites e não podemos aceitar responsabilidade por suas respectivaspolíticas de privacidade</span></p>
    <p><span>Você é livre para recusar a nossa solicitação de informações pessoais, entendendo que talvez não possamos fornecer alguns dos serviços desejados.</span></p>
    <p><span>O uso continuado de nosso site será considerado como aceitação de nossas práticas em torno de privacidade e informações pessoais. Se você tiver alguma dúvida sobre como lidamos com dados do usuário e informações pessoais, entre em contacto connosco.</span></p>
    <p>
      <span>
      <ul>
        <li><span>O serviço Google AdSense que usamos para veicular publicidade usa um cookie DoubleClick para veicular anúncios mais relevantes em toda a Web e limitar o número de vezes que um determinado anúncio é exibido para você.</span></li>
        <li><span>Para mais informações sobre o Google AdSense, consulte as FAQs oficiais sobre privacidade do Google AdSense.</span></li>
        <li><span>Utilizamos anúncios para compensar os custos de funcionamento deste site e fornecer financiamento para futuros desenvolvimentos. Os cookies de publicidade comportamental usados ​​por este site foram projetados para garantir que você forneça os anúncios mais relevantes sempre que possível, rastreando anonimamente seus interesses e apresentando coisas semelhantes que possam ser do seu interesse.</span></li>
        <li><span>Vários parceiros anunciam em nosso nome e os cookies de rastreamento de afiliados simplesmente nos permitem ver se nossos clientes acessaram o site através de um dos sites de nossos parceiros, para que possamos creditá-los adequadamente e, quando aplicável, permitir que nossos parceiros afiliados ofereçam qualquer promoção que pode fornecê-lo para fazer uma compra.</span></li>
      </ul>
      <p><br></p>
      </span>
    </p>
    <h3 class="text-xl"><span>Compromisso do Usuário</span></h3>
    <p><span>O usuário se compromete a fazer uso adequado dos conteúdos e da informação que o Vídeo Machine Pro oferece no site e com caráter enunciativo, mas não limitativo:</span></p>
    <ul>
      <li><span>A) Não se envolver em atividades que sejam ilegais ou contrárias à boa fé a à ordem pública;</span></li>
      <li><span>B) Não difundir propaganda ou conteúdo de natureza racista, xenofóbica, ou azar, qualquer tipo de pornografia ilegal, de apologia ao terrorismo ou contra os direitos humanos;</span></li>
      <li><span>C) Não causar danos aos sistemas físicos (hardwares) e lógicos (softwares) do Vídeo Machine Pro, de seus fornecedores ou terceiros, para introduzir ou disseminar vírus informáticos ou quaisquer outros sistemas de hardware ou software que sejam capazes de causar danos anteriormente mencionados.</span></li>
    </ul>
    <h3 class="text-xl"><span>Mais informações</span></h3>
    <p><span>Esperemos que esteja esclarecido e, como mencionado anteriormente, se houver algo que você não tem certeza se precisa ou não, geralmente é mais seguro deixar os cookies ativados, caso interaja com um dos recursos que você usa em nosso site.</span></p>
    <p><span>Esta política é efetiva a partir de&nbsp;21 December 2022 12:22</span></p>

  </div><!-- Fim Div Central -->

  <div></div><!-- Div Da Direita Vazia -->

</div><!-- Fim Da Parte Preta -->

{% endblock conteudo %}

{% block rodape %}
  {% include 'clientes/pages/rodape.html' %}
{% endblock rodape %}

clientes/templates/clientes/pages/redirect_whatsapp.html
{% extends 'global/frontend.html' %}
{% load static %}

{% block titulo %}Igor Lemões{% endblock titulo %}

{% block pixel %}
<!-- Taboola Pixel Code -->
<script>
  _tfa.push({notify: 'event', name: 'view_content', id: 1513773});
</script>
<!-- End of Taboola Pixel Code -->
{% endblock pixel %}

{% block conteudo %}

<div class="grid grid-cols-5 p-6 min-h-screen items-center">
  <div class="col-span-5 text-center content-center">
    <img class="inline" src="{% static 'global/imgs/loading.gif' %}"/>
  </div>

</div>


<script>
  setTimeout('Redirect()', 1000);
  function Redirect() 
  {  
      window.location="https://api.whatsapp.com/send?phone=5551997234827&text=Quero%20saber%20mais%20sobre%20o%20rob%C3%B4%20que%20edita%20v%C3%ADdeos..."; 
  } 
</script>


{% endblock conteudo %}

clientes/templates/clientes/pages/rodape.html
<!-- ############################################################################################# -->
<!-- ############################################################################################# -->
<!-- ############################################################################################# -->

<!-- Final Parte Preta -->
<!-- Final Parte Preta -->
<div class="grid grid-cols-5 p-6 items-center bg-gray-800">

    <div></div><!-- Div Da Esquerda Vazia -->
  
    <!-- Div Central Onde Vai Todo o Centeúdo -->
    <div class="col-span-5 text-white lg:col-span-3 space-y-4">
      <div class="flex">
          <div class="w-full">
            <p>
  
              NOME EMPRESARIAL: Igor Lemões
            </p>
            <p>
  
              NOME FANTASIA: Vídeo Machine Pro
            </p>
            <p>
  
              CPF: 004.864.090-58
            </p>
            <p>
              TELEFONE: <a href="{% url 'clientes:redirect_whatsapp' %}" class="underline">
              +55 51 99723-4827
              </a>
            </p>
            <p>
              E-MAIL: contato@igorlemoes.com.br
            </p>
  
          </div>
          <div class="lg:w-96 flex flex-col text-end content-end">
            <a href="{% url 'clientes:video_machine_pro' %}" class="underline">
            Início
            </a>
            <a href="{% url 'clientes:politicas' %}" class="underline">
            Políticas de privacidade
            </a>
            <a href="{% url 'clientes:termos' %}" class="underline">
            Termos de uso
            </a>
          </div>
      </div>
    </div><!-- Fim Div Central -->
  
    <div>
    </div><!-- Div Da Direita Vazia -->
  
  </div><!-- Fim Da Parte Preta -->